# Generated by Django 4.0.4 on 2023-08-18 07:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('encuesta', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='pub_data',
            new_name='publication_date',
        ),
    ]
